"""initial_institutional_foundation_schema

Revision ID: f83d80fe9524
Revises: 
Create Date: 2026-07-16 21:33:24.750892

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f83d80fe9524'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_key', name='uq_configuration_documents_document_key')
    )
    op.create_table('department_capabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_key', sa.String(length=128), nullable=False),
    sa.Column('department_name', sa.String(length=256), nullable=False),
    sa.Column('capability_level', sa.Integer(), nullable=False),
    sa.Column('evidence_note', sa.Text(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capability_level >= 0 AND capability_level <= 6', name='ck_department_capabilities_capability_level'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_key', name='uq_department_capabilities_department_key')
    )
    op.create_table('feature_registry_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feature_key', sa.String(length=128), nullable=False),
    sa.Column('feature_name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('planned', 'scaffolded', 'implemented', 'validated', 'deprecated', name='feature_status'), nullable=False),
    sa.Column('capability_level', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('activation_state', sa.Enum('inactive', 'active', 'locked', name='feature_activation_state'), nullable=False),
    sa.Column('lock_reason', sa.Text(), nullable=True),
    sa.Column('dependencies', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(activation_state::text <> 'locked') OR (lock_reason IS NOT NULL AND length(trim(lock_reason)) > 0)", name='ck_feature_registry_entries_lock_reason_required'),
    sa.CheckConstraint('capability_level >= 0 AND capability_level <= 6', name='ck_feature_registry_entries_capability_level'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_key', name='uq_feature_registry_entries_feature_key')
    )
    op.create_index('ix_feature_registry_entries_activation_state', 'feature_registry_entries', ['activation_state'], unique=False)
    op.create_index('ix_feature_registry_entries_status', 'feature_registry_entries', ['status'], unique=False)
    op.create_table('institutional_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_name', sa.String(length=128), nullable=False),
    sa.Column('institution_id', sa.String(length=64), nullable=False),
    sa.Column('product_version', sa.String(length=64), nullable=False),
    sa.Column('founding_date', sa.Date(), nullable=False),
    sa.Column('active_constitution_version', sa.String(length=128), nullable=False),
    sa.Column('active_operating_policy_version', sa.String(length=128), nullable=False),
    sa.Column('active_governance_version', sa.String(length=128), nullable=False),
    sa.Column('active_treasury_policy_version', sa.String(length=128), nullable=False),
    sa.Column('active_research_framework_version', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', name='uq_institutional_identities_institution_id')
    )
    op.create_table('policy_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('policy_kind', sa.Enum('constitution', 'operating', 'governance', 'treasury', 'research', 'other', name='policy_kind'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_key', name='uq_policy_documents_document_key')
    )
    op.create_table('service_health_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('healthy', 'degraded', 'unhealthy', name='health_status'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_service_health_events_observed_at', 'service_health_events', ['observed_at'], unique=False)
    op.create_index('ix_service_health_events_service_name', 'service_health_events', ['service_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_table('configuration_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_label', sa.String(length=128), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['configuration_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version_label', name='uq_configuration_versions_document_version')
    )
    op.create_index('uq_configuration_versions_one_active_per_document', 'configuration_versions', ['document_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='incident_severity'), nullable=False),
    sa.Column('status', sa.Enum('open', 'investigating', 'mitigated', 'closed', name='incident_status'), nullable=False),
    sa.Column('related_mode', sa.Enum('OFF', 'OBSERVE', 'PAPER', 'MICRO_LIVE', 'NORMAL_LIVE', 'SAFE_MODE', 'EMERGENCY_STOP', name='operating_mode'), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status::text <> 'closed') OR (closed_at IS NOT NULL)", name='ck_incidents_closed_requires_closed_at'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incidents_opened_at', 'incidents', ['opened_at'], unique=False)
    op.create_index('ix_incidents_status', 'incidents', ['status'], unique=False)
    op.create_table('operating_mode_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_mode', sa.Enum('OFF', 'OBSERVE', 'PAPER', 'MICRO_LIVE', 'NORMAL_LIVE', 'SAFE_MODE', 'EMERGENCY_STOP', name='operating_mode'), nullable=True),
    sa.Column('to_mode', sa.Enum('OFF', 'OBSERVE', 'PAPER', 'MICRO_LIVE', 'NORMAL_LIVE', 'SAFE_MODE', 'EMERGENCY_STOP', name='operating_mode'), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_operating_mode_history_changed_at', 'operating_mode_history', ['changed_at'], unique=False)
    op.create_table('policy_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_label', sa.String(length=128), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['policy_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version_label', name='uq_policy_versions_document_version')
    )
    op.create_index('uq_policy_versions_one_active_per_document', 'policy_versions', ['document_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('system_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('singleton_key', sa.String(length=32), server_default=sa.text("'current'"), nullable=False),
    sa.Column('current_mode', sa.Enum('OFF', 'OBSERVE', 'PAPER', 'MICRO_LIVE', 'NORMAL_LIVE', 'SAFE_MODE', 'EMERGENCY_STOP', name='operating_mode'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('singleton_key', name='uq_system_states_singleton_key')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('FOUNDER', 'OPERATOR', 'VIEWER', name='institutional_role'), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role', name='uq_user_roles_user_id_role')
    )
    op.create_index('ix_user_roles_role', 'user_roles', ['role'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=128), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('mode_at_time', sa.Enum('OFF', 'OBSERVE', 'PAPER', 'MICRO_LIVE', 'NORMAL_LIVE', 'SAFE_MODE', 'EMERGENCY_STOP', name='operating_mode'), nullable=True),
    sa.Column('config_version_id', sa.UUID(), nullable=True),
    sa.Column('policy_version_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['config_version_id'], ['configuration_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_action', 'audit_events', ['action'], unique=False)
    op.create_index('ix_audit_events_actor_user_id', 'audit_events', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_events_occurred_at', 'audit_events', ['occurred_at'], unique=False)
    op.create_index('ix_audit_events_resource', 'audit_events', ['resource_type', 'resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_events_resource', table_name='audit_events')
    op.drop_index('ix_audit_events_occurred_at', table_name='audit_events')
    op.drop_index('ix_audit_events_actor_user_id', table_name='audit_events')
    op.drop_index('ix_audit_events_action', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_user_roles_role', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_table('system_states')
    op.drop_index('uq_policy_versions_one_active_per_document', table_name='policy_versions', postgresql_where=sa.text('is_active = true'))
    op.drop_table('policy_versions')
    op.drop_index('ix_operating_mode_history_changed_at', table_name='operating_mode_history')
    op.drop_table('operating_mode_history')
    op.drop_index('ix_incidents_status', table_name='incidents')
    op.drop_index('ix_incidents_opened_at', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('uq_configuration_versions_one_active_per_document', table_name='configuration_versions', postgresql_where=sa.text('is_active = true'))
    op.drop_table('configuration_versions')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_service_health_events_service_name', table_name='service_health_events')
    op.drop_index('ix_service_health_events_observed_at', table_name='service_health_events')
    op.drop_table('service_health_events')
    op.drop_table('policy_documents')
    op.drop_table('institutional_identities')
    op.drop_index('ix_feature_registry_entries_status', table_name='feature_registry_entries')
    op.drop_index('ix_feature_registry_entries_activation_state', table_name='feature_registry_entries')
    op.drop_table('feature_registry_entries')
    op.drop_table('department_capabilities')
    op.drop_table('configuration_documents')
    # Native enum types persist after DROP TABLE; remove explicitly for clean re-upgrade.
    for enum_name in (
        "institutional_role",
        "operating_mode",
        "feature_status",
        "feature_activation_state",
        "policy_kind",
        "health_status",
        "incident_severity",
        "incident_status",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
    # ### end Alembic commands ###
